use testebulla;

CREATE TABLE users(

id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(255) NOT NULL,
endereco VARCHAR(255) NOT NULL,
telefone VARCHAR(10) NULL,
cidade VARCHAR(20) NOT NULL,
estado CHAR(2) NOT NULL,
PRIMARY KEY (`id`)

);
